export const UPDATE_PLAYERS = "UPDATE_PLAYERS";
export const UPDATE_GAMES = "UPDATE_GAMES";
export const UPDATE_CURRENT_PLAYER = "UPDATE_CURRENT_PLAYER";
export const UPDATE_CURRENT_GAME = "UPDATE_CURRENT_GAME";
