export const UPDATE_PLAYERS = "UPDATE_PLAYERS";
export const UPDATE_GAMES = "UPDATE_GAMES";
export const UPDATE_CURRENT_PLAYERS_WALLET = "UPDATE_CURRENT_PLAYERS_WALLET";
export const UPDATE_CURRENT_GAME = "UPDATE_CURRENT_GAME";
